spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.rigtmanagement.demo.entity
  #  mapper-locations: classpath*:/mapping/PmsBrandMapper.xml
  mapper-locations: classpath*:/mapper/*.xml

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

#  安全访问白名单
secure:
  ignored:
    urls:#安全路径白名单
    -/swagger-ui.html
    -/swagger-resources/**
    -/swagger/**
