spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.rigtmanagement.demo.entity
  #  mapper-locations: classpath*:/mapping/PmsBrandMapper.xml
  mapper-locations: classpath*:/mapper/*.xml